import prisma from "../db/prisma";
import { hashPassword } from "../utils/password";
import { config } from "../config";
import { randomBytes } from "crypto";

const DEFAULT_SUPER_ADMIN = {
  email: config.superAdminEmail || "admin@scs.local.invalid",
  adminType: process.env.SUPER_ADMIN_TYPE || "ROOT",
};

let cachedSuperAdminId: string | null = null;

export async function ensureDefaultSuperAdmin() {
  if (cachedSuperAdminId) return cachedSuperAdminId;

  let password = config.superAdminPassword;

  if (!password) {
    if (config.nodeEnv === "production") {
      throw new Error(
        "SUPER_ADMIN_PASSWORD is required in production environment",
      );
    }
    // Development: generate a strong random password and warn the developer
    password = randomBytes(16).toString("hex");
    // eslint-disable-next-line no-console
    console.warn(
      "No SUPER_ADMIN_PASSWORD provided; creating development super-admin with autogenerated password. Change or set SUPER_ADMIN_PASSWORD for deterministic credentials.",
    );
    // eslint-disable-next-line no-console
    console.warn(`Super admin email=${DEFAULT_SUPER_ADMIN.email}`);
    // eslint-disable-next-line no-console
    console.warn(`Super admin password=${password}`);
  }

  const superAdmin = await prisma.superAdmin.upsert({
    where: { email: DEFAULT_SUPER_ADMIN.email },
    update: {},
    create: {
      email: DEFAULT_SUPER_ADMIN.email,
      adminType: DEFAULT_SUPER_ADMIN.adminType,
      passwordHash: await hashPassword(password),
    },
    select: { id: true },
  });

  cachedSuperAdminId = superAdmin.id;
  return cachedSuperAdminId;
}
