import prisma from "../db/prisma";
import { hashPassword } from "../utils/password";

const DEFAULT_TENANT = {
  businessName: "shop1",
  ownerName: "System",
  email: "shop1@local.invalid",
  phone: null,
  gstNumber: null,
};

import { config } from "../config";
import { randomBytes } from "crypto";

let DEFAULT_OWNER_PASSWORD = process.env.DEFAULT_OWNER_PASSWORD;
if (!DEFAULT_OWNER_PASSWORD) {
  if (config.nodeEnv === "production") {
    throw new Error(
      "DEFAULT_OWNER_PASSWORD must be set in production environment",
    );
  }
  DEFAULT_OWNER_PASSWORD = randomBytes(8).toString("hex");
  // eslint-disable-next-line no-console
  console.warn(
    "No DEFAULT_OWNER_PASSWORD provided; creating development tenant owners with autogenerated password.",
  );
}

let cachedDefaultTenantId: string | null = null;

export async function ensureDefaultTenant() {
  if (cachedDefaultTenantId) return cachedDefaultTenantId;

  const tenant = await prisma.tenant.upsert({
    where: { email: DEFAULT_TENANT.email },
    update: {},
    create: DEFAULT_TENANT,
    select: { id: true },
  });

  await prisma.user.upsert({
    where: { email: DEFAULT_TENANT.email },
    update: {
      tenantId: tenant.id,
    },
    create: {
      tenantId: tenant.id,
      email: DEFAULT_TENANT.email,
      passwordHash: await hashPassword(DEFAULT_OWNER_PASSWORD),
    },
  });

  cachedDefaultTenantId = tenant.id;
  return cachedDefaultTenantId;
}

export async function getDefaultTenantId() {
  return ensureDefaultTenant();
}

export async function ensureOwnerAccounts() {
  const tenants = await prisma.tenant.findMany({
    select: {
      id: true,
      email: true,
    },
  });

  await Promise.all(
    tenants.map(async (tenant) =>
      prisma.user.upsert({
        where: { email: tenant.email },
        update: {
          tenantId: tenant.id,
        },
        create: {
          tenantId: tenant.id,
          email: tenant.email,
          passwordHash: await hashPassword(DEFAULT_OWNER_PASSWORD),
        },
      }),
    ),
  );
}
